name: Publish Docker image 

on: 
  push:
    branches: [master]

env: 
  REGISTRY: ghcr.io 
  IMAGE_NAME: ${{ github.repository }}

jobs: 
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 

    steps:
      - uses: actions/checkout@v3

      - uses: docker/login-action
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action
        id: meta
        with: 
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          tags: latest

      - uses: docker/build-push-action
        with: 
          context: .
          push: true 
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
